env:
  global:
  - LC_CTYPE=en_US.UTF-8
branches:
  only:
    - master
matrix:
  include:
  - os: osx
    language: objective-c
    osx_image: xcode8.2
    before_install:
    - brew update
    - brew install llvm
    - sudo gem install xcpretty
    script:
      - xcodebuild -scheme Trill -IDECustomDerivedDataLocation=build/DerivedData | xcpretty
      - swift utils/run-examples.swift
