env:
  global:
  - LC_CTYPE=en_US.UTF-8
matrix:
  include:
  - os: osx
    language: objective-c
    osx_image: xcode8
    before_install:
    - brew update
    - brew install llvm
    script:
      - xcodebuild -scheme Trill
